#!/usr/bin/python
"""
Driver for pressure transducer and oceanserver compass to measure depth and compass outputs
(heading, pitch, roll, ...)

keys parameters 
-depth: the raw measurement from the pressure transducer
-depth_calib: the depth filtered for glitches and calibrated with the pitch angle of the AUV
-depth_filt: the depth reading that is filtered by the polynomial-type (PT) filter
-depth_der: the derivative of depth that is determined from the gradient of PT filter

######################################
# TODO 

"""

import rospy
import numpy
import serial
import time
import math
from re import findall
from std_msgs.msg import String
from hardware_interfaces.msg import compass
from hardware_interfaces.msg import depth
from hardware_interfaces.msg import status

global serialPort
global pitch_callback


# Sensor positions
L_sensor = 1.2   # a location of the depth sensor w.r.t. AUV nose. [m] measured
L_ref = 0.65  # a reference point w.r.t. AUV nose [m] approximate
L_shift = L_sensor - L_ref  # [m]


def set_up_serial():
    """
    set up serial connection to ocean server device
    :return: True if the serial connection was successfully opened
    """
    global serialPort
    serialPort = serial.Serial(port='/dev/usboceanserver', baudrate='115200', timeout=0.01) # may need to change timeout if having issues!
    serialPort.bytesize = serial.EIGHTBITS
    serialPort.stopbits = serial.STOPBITS_ONE
    serialPort.parity = serial.PARITY_NONE
    print "Initialised DepthTransducer serial."
    serialPort.flushInput()
    serialPort.flushOutput()
    return serialPort.isOpen()


def listen_for_data(node_status):
    global serialPort
    global pitch_callback
    
    # rate settings and monitoring
    control_rate = 10.  # [Hz]
    control_period = 1/control_rate
    r = rospy.Rate(control_rate)
    rate_ok = True
    time_zero_status = time.time()  # control status publishing rate
    dt_status = rospy.get_param('status_timing')


    # Depth filtering and processing
    depth_array_length = 20
    Dx = numpy.zeros([depth_array_length],float) # time vector for PT filtering
    Dy = numpy.zeros([depth_array_length],float) # depth vector for PT filtering
    for i in range(0,depth_array_length): 
        Dx[i] = i
    previous_depth = 0  # for removing glitches, compare current sensor read to previous
    depth_glitch_delta = rospy.get_param('depth/GlitchDelta')
    depth_base = None  # for calibrating the depth sensor: ensuring zero depth when launch at surface
    pitch_callback = 0.  # use xsens pitch angle for pitch angle correction

    # Oceanserver pitch filtering and processing
    pitch_array_length = 10
    Px = numpy.zeros([pitch_array_length],float)
    Py = numpy.zeros([pitch_array_length],float)
    for i in range(0,pitch_array_length): 
        Px[i] = i

    while not rospy.is_shutdown():
        time_ref = time.time()
        try:
            # todo: all below used to be encased in try... (see depth node) - is that needed?
            while serialPort.inWaiting() > 0 and serialPort.read(1) == '$':  #while there is data to be read - read the line...
                # publish status at status rate:
                if time.time() - time_zero_status > dt_status:
                    time_zero_status = time.time()
                    pubStatus.publish(nodeID = 5, status = node_status) # status = True?

                #data_raw = serialPort.readline(size = None, eol = '\n')
                data_raw = serialPort.readline()
                                
                data = numpy.array((findall('[-]*\d+.\d+',data_raw)), numpy.float)

                try:
                    if depth_base == None:
                        #Convert ADC value to depth value: the last term is for calibration
                        depth_base = (data[4]*42.045) - 0.15 # assume that the auv is already submerge by 0.15m
                        depth_read = 0
                    else:
                        #Convert ADC value to depth value: the last term is for calibration
                        depth_read = (data[4]*42.045) - depth_base

                    # check if a glitch to a too large value happened
                    # only a step *up* to a *larger* depth value will be detected
                    if (depth_read - previous_depth) > depth_glitch_delta:
                        depth = previous_depth
                    else:
                        depth = depth_read
                    previous_depth = depth_read  # use read value, in case of actual change it will be used next time
                    depth_calib = depth - L_shift*math.sin(pitch_callback*math.pi/180.)# depth that takes into account the pitch angle of the AUV

                    #### DEPTH FILTER ####
                    if rate_ok:
                        T = control_period
                    else:
                        T = time_elapsed
                    Dx_real = Dx * T

                    Dy[1:depth_array_length] = Dy[0:(depth_array_length-1)]
                    Dy[0] = depth_calib
                    [der, depth_filt] = numpy.polyfit(Dx_real, Dy, 1)
                    depth_der = -der
                    # depth_filt = depth  # DEBUGGING

                    depth_msg.depth = depth_read   # the depth that is directly determined from a static pressure.
                    depth_msg.depth_calib = depth_calib   # the depth with filtered glitches and pitch angle correction
                    depth_msg.depth_filt = depth_filt   # depth_calib that is filtered by PT-filter.
                    depth_msg.depth_der = depth_der   # derivative of depth_calib: a by-product of the PT-filter.

                    # Publish data
                    pub_depth.publish(depth_msg)

                except ValueError:
                    print 'trying to read depth: not a float'

                # separate try for reading other, non-depth data, so this doesn't break the existing functioning depth
                try:

                    pitch_raw = data[2]
                    pitch = pitch_raw-180
                    if pitch <-180:
                        pitch=pitch%360
                    # pitch = pitch_raw  # DEBUGGING
                    
                    roll_raw = data[1]
                    roll = - roll_raw
                    
                    # roll = roll_raw
                              
                    temperature = data[3]          
                                        
                    m           = data[5]
                    mx          = data[7]
                    my          =-data[6]
                    mz          =-data[8]
                    
                    mx_raw      = data[6]
                    my_raw      = data[7]
                    mz_raw      = data[8]
                    
                    mx = mx_raw
                    my = my_raw
                    mz = mz_raw

                    heading     = calibrate(mx_raw,my_raw,mz_raw, pitch_raw, roll_raw)
                    
                    a           = data[9]
                    ax          = data[11]
                    ay          =-data[10]
                    az          =-data[12]
                                        

                    #### PITCH FILTER ####
                    Px_real = Px * T
                    Py[1:pitch_array_length] = Py[0:(pitch_array_length-1)]
                    Py[0] = pitch
                    [der, pitch_filt] = numpy.polyfit(Px_real, Py, 1)
                    pitch_der = -der
                                        
                    print '*******'
                    print 'heading %f' %(heading)
#                    print 'pitch %f' %(pitch)                    
                    print 'pitch (filtered) %f' %(pitch)
#                    print 'pitch_der (filtered) %f' %(pitch_der)
                    print 'roll %f' %(roll)
                    print 'temperature %f' %(temperature)
#                    print 'depth %f' %(depth)
                    print 'depth (filtered) %f' %(depth)
#                    print 'depth_der (filtered) %f' %(depth_der)
#                    print 'm %f' %(m)
#                    print 'mx %f' %(mx)
#                    print 'my %f' %(my)
#                    print 'mz %f' %(mz)
#                    print 'a %f' %(a)
#                    print 'ax %f' %(ax)
#                    print 'ay %f' %(ay)
#                    print 'az %f' %(az)
     

                    oceanserver_compass_msg.heading = heading
                    oceanserver_compass_msg.pitch = pitch
                    oceanserver_compass_msg.roll = roll
                    oceanserver_compass_msg.temperature = temperature
                    oceanserver_compass_msg.ax = ax
                    oceanserver_compass_msg.ay = ay
                    oceanserver_compass_msg.az = az
                    # currently unused values: m, mx,my,mz,a,pitch_filt, pitch_der
                    pub_oceanserver_compass.publish(oceanserver_compass_msg)

                except ValueError: 
                    print 'Processing oceanserver compass data: not a float'
                
        except:
            print 'read error'
        
        time_elapsed = time.time() - time_ref
        if time_elapsed < control_period:
            rate_ok = True
            r.sleep()
        else:
            rate_ok = False
            str = "depth_transducer rate does not meet the desired value of %.2fHz: actual control rate is %.2fHz" %(control_rate,1/time_elapsed)
            rospy.logwarn(str)
            pubMissionLog.publish(str)


def compass_callback(data):
    global pitch_callback
    pitch_callback = data.pitch # pitch angle measured by xsens


def calibrate(mx,my,mz, pitch, roll):

    pitch = numpy.radians(roll)
    roll  = numpy.radians(pitch)

    U = numpy.matrix([[0.00583711864398940, 0.000619779486949836, 9.27558703674774e-06],
                      [0, 0.00478543996712305, -2.33933064978229e-06],
                      [0, 0, 6.05590876286348e-05]])
    
    c = numpy.matrix([[-51.8129873735954], [-27.4232376953900], [13686.8142270094]])
    v = numpy.matrix([[mx], [my], [mz]])
    w = numpy.dot(U, (v - c))  # Normalised m terms
    eqn22_topline = (w[2]*numpy.sin(roll) - w[1]*numpy.cos(roll))
    eqn22_botline = (w[0]*numpy.cos(pitch) + w[1]*numpy.sin(pitch)*numpy.sin(roll)
                     + w[2]*numpy.sin(pitch)*numpy.cos(roll))
    
    heading2 = math.atan2(eqn22_topline,eqn22_botline)*180/numpy.pi
    heading3 = (-heading2 + 90)%360
    
    return heading3
    
    
################################################################

def validDataCheck():

    attempts = 1
    
    while attempts < 5:
        
        while not serialPort.read(1) == '$':
            pass
        #The following line has been left for clarity of the change required with new Python versions
        #dataRaw = serialPort.readline(size = None, eol = '\n')   #This line MUST be left commented!
        #The following line contains the actual change required with Python v2.6+; the command reads in line of the data
        dataRaw = serialPort.readline()  #serialIO.readline()
        #dataRaw = serialPort.readline(size = None, eol = '\n')		#Read in line of data
        data = findall('[-]*\d+.\d+',dataRaw)
        print data
        if len(data) == 13:
            return True
    
    return False
    
################################################################
def shutdown():
    serialPort.flushInput()
    serialPort.flushOutput()
    pubStatus.publish(nodeID = 5, status = False)
    serialPort.close()

################################################################        
#     INITIALISE     ###########################################
################################################################

if __name__ == '__main__':
    time.sleep(1) #Allow System to come Online    
    rospy.init_node('OceanServer_compass')
    
    global pub
    global serialPort
    depth_msg = depth()
    oceanserver_compass_msg = compass()
    
    pub_depth = rospy.Publisher('depth_out', depth)
    pub_oceanserver_compass = rospy.Publisher('oceanserver_compass', compass)
    pubMissionLog = rospy.Publisher('MissionStrings', String)
    rospy.Subscriber('compass_out', compass, compass_callback) 
    pubStatus = rospy.Publisher('status', status)
    
    rospy.on_shutdown(shutdown)
    
    port_status = set_up_serial()
    log_str = "OceanServer port status = %s. Port = %s" %(port_status, serialPort.portstr)
    rospy.loginfo(log_str)
    time.sleep(0.3)
    string_status=validDataCheck()
    
    if (port_status and string_status) == True:    
        status = True
        pubStatus.publish(nodeID = 5, status = status)
        rospy.loginfo("OceanServer compass online")
        rospy.loginfo("Depth transducer online")
    else:
        status = False
        pubStatus.publish(nodeID = 5, status = status)

    # TODO: at the moment this doesn't seem to deal with serial not being set-up?
    # it will just listen for data, even though clearly nothing would happen?!

    listen_for_data(status)   #Main loop for receiving data
