#!/usr/bin/python
"""
Simple plotter for visualising sonar data live/from rosbag
 current plots:
 * live stream of all bins recorded (bins vs time)
 * polar plot using the most recent bins available for each angle (polar bins)
 

#############################################################
# TODO
 - make the figure zoom/drag etc. work again

"""

import rospy
import numpy
import time
import sys
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui, QtCore
import signal

from std_msgs.msg import String
from hardware_interfaces.msg import depth
from dynamic_reconfigure.server import Server

from hardware_interfaces import sonar_analyse
from hardware_interfaces import sonar_plot
from hardware_interfaces.cfg import SonarConfigConfig

################################################################

def get_sonar(msgData):
    global depth
    """ add sonar data to sonar object as it comes in from ROS messages as *msgData*
    """
    ping = sonar_analyse.SonarPing(msgData)
    plotData.add_data(ping)
    # update obstacle detection
    targetDetection, detections = analyseData.detect_obstacle(ping, depth)
    plotData.targetRange.append(targetDetection[1])
    plotData.Detections.append(detections)


def draw_figures():
    """
    setup the Qt Window so it updates regularly and all settings are as wished
    """

    # make sure that ctrl+c quits:
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    app = QtGui.QApplication(sys.argv)
    win = QtGui.QWidget()
    grid = QtGui.QGridLayout()    
    win.setLayout(grid)

    ## define all plots in the window
    w = 20
    # bins vs time
    bins_vs_time = pg.ImageView()
    grid.addWidget(bins_vs_time, 1, 1, 2*w, 2*w)

    # polar bins
    polar_bins = pg.ImageView()
    grid.addWidget(polar_bins, 1, 2*w + 1, 4*w, 4*w)

    label_0deg = QtGui.QLabel()
    label_0deg.setText("0 degrees")
    label_0deg.setStyleSheet('color: yellow')

    label_90deg = QtGui.QLabel()
    label_90deg.setText("90 degrees")
    label_90deg.setStyleSheet('color: yellow')

    label_180deg = QtGui.QLabel()
    label_180deg.setText("180 degrees")
    label_180deg.setStyleSheet('color: yellow')

    label_270deg = QtGui.QLabel()
    label_270deg.setText("270 degrees")
    label_270deg.setStyleSheet('color: yellow')

    label_range = QtGui.QLabel()
    label_range.setText("Range: " + str(plotData.pingRange[-1]))
    label_range.setStyleSheet('color: orange')


    grid.addWidget(label_90deg,         1, 4 * w, 4, 20)
    grid.addWidget(label_180deg,    2 * w, 2 * w + 5, 4, 20)
    grid.addWidget(label_270deg,   4 * w - 5, 4 * w, 4, 20)
    grid.addWidget(label_0deg,   2 * w, 6 * w - 20, 4, 20)
    grid.addWidget(label_range, 1, 2*w + 1, 12, 20)


    # detected distance
    obstacle_detection = pg.PlotWidget()
    obstacle_detection.plot(plotData.targetRange)
    grid.addWidget(obstacle_detection, 2*w+3, 1, w, 2*w)



    # last couple of sonar pings
    last_pings = pg.PlotWidget()
    grid.addWidget(last_pings, 3*w+3, 1, w, 2*w)




    def update_figures():
        if len(plotData.bins) > 0:
            label_range.setText(" Range: " + str(round(plotData.pingRange[-1], 2)) +
                                "\n Angle: " + str(round(plotData.transducerBearing[-1], 2)) +
                                "\n Detection: " + str(round(plotData.targetRange[-1], 2)))
            bins_vs_time.setImage(numpy.array(plotData.bins))
            polar_bins.setImage(plotData.polarImage)
            obstacle_detection.clear()
            obstacle_detection.plot(plotData.targetRange)
            last_pings.clear()
            last_pings.setYRange(0,120)

            if len(plotData.bins) > 7:
                last_pings.plot(plotData.bins[-8], pen=(0,   0,  50))
                last_pings.plot(plotData.bins[-7], pen=(0,   0, 100))
                last_pings.plot(plotData.bins[-6], pen=(0,   0, 150))
                last_pings.plot(plotData.bins[-5], pen=(0,   0, 200))
                last_pings.plot(plotData.bins[-4], pen=(0,  50, 200))
                last_pings.plot(plotData.bins[-3], pen=(0, 100, 200))
                last_pings.plot(plotData.bins[-2], pen=(0, 150, 200))
                last_pings.plot(plotData.bins[-1], pen=(0, 250, 250))
 
                last_pings.plot(plotData.Detections[-1], pen='r')
 


    timer = QtCore.QTimer()
    timer.timeout.connect(update_figures)
    timer.start(50)
    win.show()
    QtGui.QApplication.instance().exec_()


def callback(config, level):
    rospy.logwarn(config)
    analyseData.BlankDist = config.blanking_dist
    analyseData.SlideThreshold = config.slide_threshold
    analyseData.BaseThreshold = config.base_threshold
    analyseData.MaxThreshold = config.max_threshold
    return config

def depth_callback(data):
    global depth
    depth = data.depth_filt

################################################################
################################################################
if __name__ == '__main__':

    global depth
    rospy.init_node('plot_sonar', log_level=rospy.DEBUG)
    analyseData = sonar_analyse.SonarEvaluate()
    rospy.Subscriber('sonar_output', String, get_sonar)
    rospy.Subscriber('depth_out', depth, depth_callback)
    srv = Server(SonarConfigConfig, callback)
    plotData = sonar_plot.SonarPlot()
    time.sleep(1)
    draw_figures()
    
    
  
