Header header

# internal temperature of the device [degree celsius]
float64 temperature

# three euler angles that represent the orientation of the MT[degree]
float64 orientation_roll
float64 orientation_pitch
float64 orientation_yaw

# rate of turn of the MT
float64 angular_velocity_x
float64 angular_velocity_y
float64 angular_velocity_z

# calibrated acceleration of the MT
float64 linear_acceleration_x
float64 linear_acceleration_y
float64 linear_acceleration_z
